### ISSUE TITLE
todo/current ideas

### ISSUE THREAD

**Issue by Xilef11** [Xilef11/Runes-of-Wizardry#9]
- [x] JSON export/import for patterns
- [x] Rune entity setup
  - add runeEntity field to TEDustPlaced
  - rune entity gets the set of BlockPos from patternFinder to remember all dust blocks
  - [x] sacrifices
- [ ] ~~Extra (custom) categories for guide book (i.e map<String(loc. name), Category> )~~(waiting for guide-api to update)
- [ ] ~~automatic placing of dust~~
- [x] broom item to quickly empty a dust block
- [x] remove dust with left click (raytracing?)
